FROM centos:7
RUN \
	yum -y install httpd php php-cli php-common
COPY startbootstrap-sb-admin-gh-pages /var/www/html
RUN echo "<?php phpinfo(); ?>" > /var/www/html/hola.php
CMD apachectl -DFOREGROUND
