FROM centos:7
RUN yum -y install httpd
WORKDIR /var/www/html
ADD startbootstrap-freelancer-gh-pages .
ENV contenido prueba
RUN echo "$contenido" > /var/www/html/prueba.html
CMD apachectl -DFOREGROUND
